export const devices = [
  {
    title: 'Duke Design Health',
    slug: 'duke-design-health',
    time: 'August 2025 - Present',
    description: 'I am part of an interdisciplinary team developing a medical device to improve the capabilities of stroke patient rehabilitation in a clinical setting. This involves conducting ethnographic research, assessing client needs, and collaborating across engineering and healthcare fields. The project will culminate in a user-centered prototype designed for real-world application.',
    tasks: [
      'Identify user needs for an impactful medical device by shadowing clinicians at Duke Region Hospital',
      'Design and prototype a functional medical device',
      'Create a business plan for the device, taking into account regulatory and manufacturing processes',
    ],
    skills: ['User-Needs Identification', 'Ethnographic Research', 'Fusion360 CAD', 'Medical Device Prototyping', 'FDA Regulatory Assessments', 'Team Collaboration'],
    images: ['images/design-health.jpg'],
  },
  {
    title: 'Interferometric Chamber (InCh)',
    slug: 'inch',
    description: 'Working for the Biomedical Interferometry Optical and Spectroscopy Lab at Duke, I have been tasked with transforming a novel quantitative phase imaging system into a low-cost diagnostic tool using my expertise in opto-mechanical design. This Interferometric Chamber (InCh) aims to enhance the visualization of sickle cell disease morphology, to enable high-throughput diagnostics in low-resource healthcare settings. One of the greatest engineering challenges lies in preserving optical stability and functionality while adapting the system for low-cost commercialization.',
    time: 'September 2025 - Present',
    tasks: [
      'Use photoresist to create a novel mold for microfluidic fabrication',
      'Validate and characterizing sickle cell diagnostics using quantitative phase imaging',
      'Adapt a quantitative imaging system for low-cost manufacturing',
      'Design and construct an instrument with structural and optical integrity',
    ],
    skills: ['Microfluidic Chip Fabrication', 'Fusion360 CAD', 'Opto-Mechanical Prototyping', 'Quantitative Phase Imaging', 'Interdisciplinary Research'],
    images: ['images/BIOS.jpg'],
  },
  {
    title: 'Cystoscope Redesign',
    slug: 'cystoscope-redesign',
    time: 'August 2025 - Present',
    description: 'This medical device design project is part of the Advanced Design and Manufacturing course at Duke, aimed at designing and modeling a cystoscope. The ongoing goal is to 3-D model a new cystoscope design, taking into consideration device function, industrial design, manufacturing processes, structural integrity, and assembly requirements. From this project, I have strengthened my technical skills in CAD but also gained a greater understanding of the overall design and prototyping process.',
    tasks: [
      'Sketch orthogonal and 3D perspectives of a redesigned cystoscope',
      'Design a new cystoscope, including electrical, water, and assembly features',
      'Create 3D models from 2D medical images',
      'Select appropriate device materials to accommodate various manufacturing methods',
    ],
    skills: ['Fusion 360', 'Medical Device Prototyping', 'Designing for Manufacturing'],
    images: ['images/cytoscope-half.jpg', 'images/cytoscope-whole.jpg'],
  },
  {
    title: 'MII-OCT',
    slug: 'mii-oct',
    time: 'September 2024 - June 2025',
    description: 'As part of my senior design project in the Optical Neural Imaging Lab at UC Riverside, I built a system that integrates optical coherence tomography (OCT) with an upright brightfield microscope to enable multimodal imaging of tissue samples. This advancement enhances imaging efficiency, improves spatial alignment, and streamlines data acquisition, providing researchers with a more effective tool for comprehensive tissue analysis. The project culminated in a functional and impactful medical device that enabled simultaneous brightfield and OCT imaging, which we presented at the UCR Senior Design showcase.',
    tasks: [
      'Identified user needs, addressable market, and design specifications',
      'Researched imaging systems and the optical setup necessary to achieve the performance criteria and overcome engineering constraints',
      'Prototyped opto-mechanical components with accurate tolerance and precision',
      'Utilized iterative prototyping to construct a stable device',
      'Conducted statistical validations for optical functions and design specifications for each component',
    ],
    skills: ['Optical Coherence Tomography', 'SolidWorks CAD', 'Opto-Mechanical Prototyping', 'MATLAB', 'Optics Alignment', 'Component Validation', 'FDA Regulatory Assessment', 'Statistical Analysis', 'Project Leadership', 'Problem-Solving'],
    images: ['images/MII-OCT-device.jpg', 'images/MII-OCT-poster.jpg', 'images/MII-OCT-machine.jpg', 'images/MII-OCT-pres.jpg'],
  },
  {
    title: 'Mindful Matchup',
    slug: 'mindful-matchup',
    time: 'June 2023 - July 2023',
    description: 'As part of Keck Graduate Institute\'s Medical Device Development Internship, I collaborated with a dynamic team to design, manufacture, and code an interactive device aimed at increasing neuroplasticity in early-stage dementia patients. I contributed expertise in Python-based user interfaces, electrical engineering, and iterative prototyping to deliver a functional and impactful prototype. This project\'s greatest challenge was optimizing the interactions of all components to meet stringent design specifications and user considerations.',
    tasks: [
      'Conducted background research on dementia treatment and progression',
      'CAD modeled a patient-focused device',
      'Manufactured and assembled a function device using 3-D printing, resin printing, and laser cutting',
      'Used Python to create a customizable game and user interface',
    ],
    skills: ['Python', 'Device Prototyping', 'GitHub', '3-D and Resin Printing', 'Soldering', 'Electrical Circuit Construction', 'OnShape CAD', 'Kivy', 'Team Collaboration'],
    images: ['images/mindful-render.jpg', 'images/mindful-device.jpg', 'images/mindful-wiring.jpg'],
  },
]

export const research = [
  {
    title: 'Tissue Injury and Mortality Engineering Lab',
    slug: 'time-lab',
    time: 'October 2023 - June 2025',
    description: 'As an undergraduate researcher at UC Riverside, I investigated the stress tolerance of stem cells with the goal of engineering a more resistant stem-cell therapy. To understand the stress mechanisms of genetically modified stem cells, I utilized confocal imaging and MATLAB simulation models to quantify the localization of Wnt signal pathway transcription cofactors. I also led independent experiments quantifying the toxic responses of genetically modified ASCs to environmental toxins, which I presented at UC Riverside\'s Undergraduate Symposium. This work combined computational modeling with hands-on experimentation to disseminate research findings and contribute to a deeper understanding within regenerative medicine.',
    tasks: [
      'Cultured, passaged, and froze genetically modified stem cells',
      'Conducted lentivirus transduction on ASCs to enable the expression of specific stress-resistant proteins',
      'Planned and executed experimental plans to investigate stem cell stress tolerance',
      'Imaged ASC growth in response to induced stress variables',
      'Utilized MATLAB to quantify cell counts and illustrate cell growth rate',
    ],
    skills: ['Mammalian Cell Culture', 'MATLAB', 'Confocal Microscopy', 'Fluorescence Microscopy', 'DNA Isolation', 'Data Visualization', 'Statistical Analysis', 'Experimental Planning', 'Research Presentation', 'Team Collaboration'],
    images: ['images/TIME-pres.jpg', 'images/TIME-poster.jpg'],
  },
  {
    title: 'Terasaki Institute for Biomedical Innovation',
    slug: 'terasaki-institute',
    time: 'June 2024 - September 2024',
    description: 'As a Biomedical Intern, I engaged in high-level research assessing the applications of organoids and micro-organospheres in precision medicine and oncology, while gaining insight into the innovation process of translational research. During this 12-week internship, I engaged in several projects with vast clinical and entrepreneurial implications. My work culminated in a final presentation in which I discussed my research on novel disease modeling and cell-based diagnostic applications of organoid technologies.',
    tasks: [
      'Conducted high-throughput characterization of IPSC-derived hepatocyte organoids',
      'Identified the most physiologically relevant 3-D extracellular environments for drug delivery in cancerous micro-organoids',
      'Created drug assays that utilize patient-derived microtumors',
      'Characterized the mechanical properties of hanging drop culture models',
    ],
    skills: ['3-D Cell Culturing', 'Primary Sample Processing', 'PCR', 'DNA/RNA Isolation', 'ELISA', 'Fluorescence Microscopy', 'IPSC Differentiation', 'Organoid Characterization', 'Project Prioritization', 'Experimental Documentation'],
    images: ['images/terasaki-award.jpg', 'images/terasaki-pres.jpg'],
  },
  {
    title: 'Jinkerson Lab',
    slug: 'jinkerson-lab',
    time: 'March 2022 - June 2023',
    description: 'My experiences as an avid scuba diver led me to join a chemical and environmental lab at UC Riverside focused on understanding the mechanisms of coral bleaching and increasing coral stress resilience. Using aseptic, micropipette, and microscopy techniques, I worked with the model organism Aiptasia and transitioned wildtype organisms to aposymbionts for genetic engineering experiments, contributing to environmental bioengineering research.',
    tasks: [
      'Transitioned hundreds of aiptasia to aposymbionts using menthol bleaching and cold shocks',
      'Utilized fluorescence microscopy to measure chlorophyll presence and validate aposymbiotic organisms',
    ],
    skills: ['Aseptic Technique', 'Cell Counts', 'Fluorescence Microscopy', 'Time Management'],
    images: ['images/jinkerson-graphic1.jpg', 'images/jinkerson-graphic2.jpg'],
  },
]